name: Armaea
favicon: null
layout_spectrum: 0.5895100361667573
typography_spectrum: 0.23805643850937486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.095301931258291
  lightness: 0.32134703057818115
  saturation: 0.7780835127923638
  rhythmicContrast: 0.8754734515678138
purpose: []
